---
- name: include vars
  include_vars: "{{ playbook_dir }}/config.yml"

# ssh, host setting
- include: register_hosts.yml
- include: ssh_config.yml

# clean
- name : Remove old install dir
  file : 
    path : "{{ install_dir }}"
    state: absent

- name : Create install dir
  file : 
    path : "{{ install_dir }}"
    state: directory

# install java
- include: install_java.yml