---
- name: include vars
  include_vars: "{{ playbook_dir }}/config.yml"

  # Install Java
  # Register Hosts
  # Create necessary user
  # Install custom python project
  # Configure SSH 

  # Clean
  
- name : Remove old install dir
  file : 
    path : "{{ install_dir }}"
    state: absent
  
- name : Create install dir
  file : 
    path : "{{ install_dir }}"
    state: directory


    
- include: register_hosts.yml
- include: create_user.yml
- include: ssh_config.yml
- include: install_java.yml



