---
- name: include vars
  include_vars: "{{ playbook_dir }}/config.yml"

#- include: ssh_config.yml
- name : Remove old install dir
  file : 
    path : "{{ install_dir }}"
    state: absent

- name : Create install dir
  file : 
    path : "{{ install_dir }}"
    state: directory

- include: install_java.yml

  