---
- block:
  - name: Generate SSH key
    openssh_keypair:
      path: "~/.ssh/id_rsa"
      type: rsa
      size: 4096
      state: present
      force: no
    become: True
    become_user: "{{ hadoop.user }}"

  - name: Fetch all public ssh keys
    shell: cat ~/.ssh/id_rsa.pub
    register: ssh_keys
    tags:
      - ssh
    become: True
    become_user: "{{ hadoop.user }}"
    
  - name: Check keys
    debug: msg= "{{ ssh_keys.stdout }}"
    tags:
      - ssh
  
  - name: Deploy keys on all servers
    authorized_key: 
      user: hadoop
      key: "{{ item[0] }}"
      state: present
    delegate_to: "{{ item[1] }}"
    with_nested:
      - "{{ ssh_keys.stdout }}"
      - "{{ groups['nodes']}}"
    become: True
    become_user: "{{ hadoop.user }}"

  when: inventory_hostname in groups['master']
